# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-08 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=25)),
                ('cust_address', models.CharField(help_text='Enter street number and name only', max_length=100)),
                ('cust_city', models.CharField(max_length=100)),
                ('cust_state', models.CharField(help_text='Please type the abbreviation for your state', max_length=2)),
                ('cust_zip', models.CharField(max_length=5)),
                ('cust_tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(help_text='Please enter Active, Resolved or In-progress', max_length=25)),
                ('custID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
                ('ticketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ticket_code')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket_code',
            name='t_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ticket_type'),
        ),
    ]
