# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 06:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191208_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_completed',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
