# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_ticket_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_completed',
            field=models.DateField(null=True),
        ),
    ]
