# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ticket_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_fix',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
