# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-11 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191210_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Done', 'Done'), ('In-progress', 'In-progress')], default='Active', help_text='Please enter Active, Resolved or In-progress', max_length=25),
        ),
    ]
