# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191211_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='aff_work',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High')], default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='contact',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='room_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High')], default='Low', max_length=20),
        ),
    ]
