# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191211_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_method',
            field=models.CharField(choices=[('Email', 'Email'), ('Text', 'Text'), ('Phone', 'Phone')], default='Email', max_length=14, null=True),
        ),
    ]
