# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-14 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_ticket_contact_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
