# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-14 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_ticket_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='aff_num',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
