# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191214_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_date', models.DateField()),
                ('tech_notes', models.TextField(max_length=500, null=True)),
                ('tech_status', models.CharField(choices=[('Active', 'Active'), ('Done', 'Done'), ('In-progress', 'In-progress')], default='Active', help_text='Please enter Active, Resolved or In-progress', max_length=25)),
            ],
        ),
    ]
