# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_tech_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_update',
            name='tech_ticket',
            field=models.ForeignKey(default=33, on_delete=django.db.models.deletion.CASCADE, to='app.Ticket'),
            preserve_default=False,
        ),
    ]
