# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_tech_update_tech_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='contact',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Done', 'Done'), ('In-progress', 'In-progress')], default='Not begun', help_text='Please enter Active, Resolved or In-progress', max_length=25),
        ),
    ]
